// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ethers from "ethers";

var abi = [
  "function balanceOf(address) view returns (uint)",
  "function approve(address spender, uint amount)"
];

function make(address, provider) {
  return new Ethers.Contract(address, abi, provider);
}

var ERC20 = {
  abi: abi,
  make: make
};

export {
  ERC20 ,
  
}
/* ethers Not a pure module */
