// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Ethers from "ethers";
import * as TestMaticJs from "./testMatic.js";
import * as Core from "@web3-react/core";
import * as Config$WildCards from "../../Config.bs.js";

function doTest(prim, prim$1, prim$2, prim$3) {
  return TestMaticJs.doTest(prim, prim$1, prim$2, prim$3);
}

function Matic$DaiToMaticConversion(Props) {
  var web3Context = Core.useWeb3React();
  React.useState(function () {
        
      });
  React.useEffect((function () {
          var match = web3Context.account;
          var match$1 = web3Context.library;
          var match$2 = web3Context.chainId;
          if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
            doTest(match$1.provider, new (Ethers.providers.JsonRpcProvider)("https://rpc-mumbai.matic.today"), Config$WildCards.Dai.getAddress(true, /* MainnetQuery */2, match$2, undefined), match);
          }
          
        }), [
        web3Context.account,
        web3Context.library,
        web3Context.chainId
      ]);
  return React.createElement("p", undefined, "Convert DAI on mainnet to matic");
}

var DaiToMaticConversion = {
  make: Matic$DaiToMaticConversion
};

export {
  doTest ,
  DaiToMaticConversion ,
  
}
/* react Not a pure module */
