// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TestMaticJs from "./testMatic.js";
import * as Core from "@web3-react/core";
import * as DepositTrackingJs from "./depositTracking.js";

function doTest(prim, prim$1, prim$2, prim$3) {
  return TestMaticJs.doTest(prim, prim$1, prim$2, prim$3);
}

function checkDepositStatus(prim, prim$1, prim$2, prim$3) {
  return DepositTrackingJs.checkDepositStatus(prim, prim$1, prim$2, prim$3);
}

function Matic$DaiToMaticConversion(Props) {
  var web3Context = Core.useWeb3React();
  React.useState(function () {
        
      });
  React.useEffect((function () {
          var match = web3Context.account;
          var match$1 = web3Context.library;
          var match$2 = web3Context.chainId;
          if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
            console.log(match, match$1, match$2);
            var __x = checkDepositStatus("0xFd71Dc9721d9ddCF0480A582927c3dCd42f3064C", "0x47195A03fC3Fc2881D084e8Dc03bD19BE8474E46", "1000000000000000000", "0xb5505a6d998549090530911180f38aC5130101c6");
            var __x$1 = __x.then(function (res) {
                  return Promise.resolve((console.log("a previous sync status", res), undefined));
                });
            __x$1.catch(function (err) {
                  return Promise.resolve((console.log("a previous sync status", err), undefined));
                });
          }
          
        }), [
        web3Context.account,
        web3Context.library,
        web3Context.chainId
      ]);
  return React.createElement("p", undefined, "Convert DAI on mainnet to matic");
}

var DaiToMaticConversion = {
  make: Matic$DaiToMaticConversion
};

export {
  doTest ,
  checkDepositStatus ,
  DaiToMaticConversion ,
  
}
/* react Not a pure module */
